version: "3.7"
services:
  strapi:
    image: strapi/strapi
    volumes:
      - ./packages/strapi:/srv/app
      - ./packages/strapi/node_modules:/srv/app/node_modules
  front:
    image: front:latest
    #build:
    #  context: ./packages/front
    #  dockerfile: ./packages/front/Dockerfile
    volumes:
      - ./packages/front/src:/app/src
      - ./packages/front/pages:/app/pages
  pythonapi:
    image: pythonapi:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
